-file("/Users/andrwe/.asdf/installs/erlang/28.4.1/lib/parsetools-2.7.1/include/leexinc.hrl", 0).
%%
%% %CopyrightBegin%
%%
%% SPDX-License-Identifier: BSD-2-Clause
%%
%% Copyright (c) 2008,2009 Robert Virding. All rights reserved.
%% Copyright Ericsson AB 2009-2025. All Rights Reserved.
%%
%% Redistribution and use in source and binary forms, with or without
%% modification, are permitted provided that the following conditions
%% are met:
%%
%% 1. Redistributions of source code must retain the above copyright
%% notice, this list of conditions and the following disclaimer.
%% 2. Redistributions in binary form must reproduce the above copyright
%% notice, this list of conditions and the following disclaimer in the
%% documentation and/or other materials provided with the distribution.
%%
%% THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
%% "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
%% LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
%% FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
%% COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
%% INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
%% BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
%% LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
%% CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
%% LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
%% ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
%% POSSIBILITY OF SUCH DAMAGE.
%%
%% %CopyrightEnd%
%% 

%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(mirage_css_tokenizer).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("src/mirage_css_tokenizer.xrl", 59).

drop_first([_|Rest]) ->
    Rest.

trim_and_drop_last(Chars) ->
    Trimmed = string:strip(Chars),
    Len = string:len(Trimmed),
    string:substr(Trimmed, 1, Len - 1).

remove_quotes(Chars) ->
    Len = string:len(Chars),
    string:substr(Chars, 2, Len - 2).

without_escapes(Chars) ->
    re:replace(Chars, "\\\\", "", [unicode, global, {return, list}]).

-file("/Users/andrwe/.asdf/installs/erlang/28.4.1/lib/parsetools-2.7.1/include/leexinc.hrl", 47).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

%% string(InChars) ->
%% string(InChars, Loc) ->
%% {ok,Tokens,EndLoc} | {error,ErrorInfo,EndLoc}.
%% Loc is the starting location of the token, while EndLoc is the first not scanned
%% location. Location is either Line or {Line,Column}, depending on the "error_location" option.

string(Ics) -> 
    string(Ics,1).
string(Ics,L0) -> 
    string(Ics, L0, 1, Ics, []).
string(Ics, L0, C0, Tcs, Ts) -> 
    case do_string(Ics, L0, C0, Tcs, Ts) of
        {ok, T, {L,_}} -> {ok, T, L};
        {error, {{EL,_},M,D}, {L,_}} ->
            EI = {EL,M,D},
            {error, EI, L}
    end.

do_string([], L, C, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),{L,C}};
do_string(Ics0, L0, C0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, C0, 0, reject, 0) of
        {A,Alen,Ics1,L1,_C1} ->                  % Accepting end state
            C2 = adjust_col(Tcs, Alen, C0),
            string_cont(Ics1, L1, C2, yyaction(A, Alen, Tcs, L0, C0), Ts);
        {A,Alen,Ics1,L1,_C1,_S1} ->              % Accepting transition state
            C2 = adjust_col(Tcs, Alen, C0),
            string_cont(Ics1, L1, C2, yyaction(A, Alen, Tcs, L0, C0), Ts);
        {reject,_Alen,Tlen,_Ics1,_L1,_C1,_S1} ->  % After a non-accepting state
            {error,{{L0, C0} ,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},{L0, C0}};
        {A,Alen,Tlen,_Ics1,L1, C1,_S1}->
            Tcs1 = yysuf(Tcs, Alen),
            L2 = adjust_line(Tlen, Alen, Tcs1, L1),
            C2 = adjust_col(Tcs, Alen, C1),
            string_cont(Tcs1, L2, C2, yyaction(A, Alen, Tcs, L0,C0), Ts)
    end.

%% string_cont(RestChars, Line, Col, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

-dialyzer({nowarn_function, string_cont/5}).

string_cont(Rest, Line, Col, {token,T}, Ts) ->
    do_string(Rest, Line, Col, Rest, [T|Ts]);
string_cont(Rest, Line, Col, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    do_string(NewRest, Line, Col, NewRest, [T|Ts]);
string_cont(Rest, Line, Col, {end_token,T}, Ts) ->
    do_string(Rest, Line, Col, Rest, [T|Ts]);
string_cont(Rest, Line, Col, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    do_string(NewRest, Line, Col, NewRest, [T|Ts]);
string_cont(Rest, Line, Col, skip_token, Ts) ->
    do_string(Rest, Line, Col, Rest, Ts);
string_cont(Rest, Line, Col, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    do_string(NewRest, Line, Col, NewRest, Ts);
string_cont(_Rest, Line, Col, {error,S}, _Ts) ->
    {error,{{Line, Col},?MODULE,{user,S}},{Line,Col}}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Loc) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,CurrCol,TokenChars,TokenLen,TokenLine,TokenCol,AccAction,AccLen}

token(Cont,Chars) -> 
    token(Cont,Chars,1).
token(Cont, Chars, Line) -> 
    case do_token(Cont,Chars,Line,1) of
        {more, _} = C -> C;
        {done, Ret0, R} ->
            Ret1 = case Ret0 of
                {ok, T, {L,_}} -> {ok, T, L};
                {eof, {L,_}} -> {eof, L};
                {error, {{EL,_},M,D},{L,_}} -> {error, {EL,M,D},L}
            end,
            {done, Ret1, R}
    end.

do_token([], Chars, Line, Col) ->
    token(yystate(), Chars, Line, Col, Chars, 0, Line, Col, reject, 0);
do_token({token,State,Line,Col,Tcs,Tlen,Tline,Tcol,Action,Alen}, Chars, _, _) ->
    token(State, Chars, Line, Col, Tcs ++ Chars, Tlen, Tline, Tcol, Action, Alen).

%% token(State, InChars, Line, Col, TokenChars, TokenLen, TokenLine, TokenCol
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, C0, Tcs, Tlen0, Tline, Tcol, A0, Alen0) ->
    case yystate(S0, Ics0, L0, C0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1,C1} ->
            C2 = adjust_col(Tcs, Alen1, C1),
            token_cont(Ics1, L1, C2, yyaction(A1, Alen1, Tcs, Tline,Tcol));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,C1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,C1,Tcs,Alen1,Tline,Tcol,A1,Alen1}};
        {A1,Alen1,Ics1,L1,C1,_S1} ->               % Take what we got
            C2 = adjust_col(Tcs, Alen1, C1),
            token_cont(Ics1, L1, C2, yyaction(A1, Alen1, Tcs, Tline,Tcol));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,C1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,C1,Tcs,Tlen1,Tline,Tcol,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,C1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{{Tline,Tcol},?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},{L1,C1}};
                     true -> {eof,{L1,C1}}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,_L1,_C1,_S1} ->    % No token match
            Error = {{Tline,Tcol},?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,{Tline,Tcol}},Ics1};
        {A1,Alen1,Tlen1,_Ics1,L1,_C1,_S1} ->       % Use last accept match
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            C2 = C0 + Alen1,
            token_cont(Tcs1, L2, C2, yyaction(A1, Alen1, Tcs, Tline, Tcol))
    end.

%% token_cont(RestChars, Line, Col, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

-dialyzer({nowarn_function, token_cont/4}).

token_cont(Rest, Line, Col, {token,T}) ->
    {done,{ok,T,{Line,Col}},Rest};
token_cont(Rest, Line, Col, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,{Line,Col}},NewRest};
token_cont(Rest, Line, Col, {end_token,T}) ->
    {done,{ok,T,{Line,Col}},Rest};
token_cont(Rest, Line, Col, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,{Line,Col}},NewRest};
token_cont(Rest, Line, Col, skip_token) ->
    token(yystate(), Rest, Line, Col, Rest, 0, Line, Col, reject, 0);
token_cont(Rest, Line, Col, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, reject, 0);
token_cont(Rest, Line, Col, {error,S}) ->
    {done,{error,{{Line, Col},?MODULE,{user,S}},{Line, Col}},Rest}.

%% tokens(Continuation, Chars) ->
%% tokens(Continuation, Chars, Loc) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,CurrCol,TokenChars,TokenLen,TokenLine,TokenCur,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,CurrCol,TokenChars,TokenLen,TokenLine,TokenCur,Error,AccAction,AccLen}

tokens(Cont,Chars) -> 
    tokens(Cont,Chars,1).
tokens(Cont, Chars, Line) -> 
    case do_tokens(Cont,Chars,Line,1) of
        {more, _} = C -> C;
        {done, Ret0, R} ->
            Ret1 = case Ret0 of
                {ok, T, {L,_}} -> {ok, T, L};
                {eof, {L,_}} -> {eof, L};
                {error, {{EL,_},M,D},{L,_}} -> {error, {EL,M,D},L}
            end,
            {done, Ret1, R}
    end.

do_tokens([], Chars, Line, Col) ->
    tokens(yystate(), Chars, Line, Col, Chars, 0, Line, Col, [], reject, 0);
do_tokens({tokens,State,Line,Col,Tcs,Tlen,Tline,Tcol,Ts,Action,Alen}, Chars, _,_) ->
    tokens(State, Chars, Line, Col, Tcs ++ Chars, Tlen, Tline, Tcol, Ts, Action, Alen);
do_tokens({skip_tokens,State,Line, Col, Tcs,Tlen,Tline,Tcol,Error,Action,Alen}, Chars, _,_) ->
    skip_tokens(State, Chars, Line, Col, Tcs ++ Chars, Tlen, Tline, Tcol, Error, Action, Alen).

%% tokens(State, InChars, Line, Col, TokenChars, TokenLen, TokenLine, TokenCol,Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, C0, Tcs, Tlen0, Tline, Tcol, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, C0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1,C1} ->
            C2 = adjust_col(Tcs, Alen1, C1),
            tokens_cont(Ics1, L1, C2, yyaction(A1, Alen1, Tcs, Tline, Tcol), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,C1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,C1,Tcs,Alen1,Tline,Tcol,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,C1,_S1} ->               % Take what we got
            C2 = adjust_col(Tcs, Alen1, C1),
            tokens_cont(Ics1, L1, C2, yyaction(A1, Alen1, Tcs, Tline,Tcol), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,C1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,C1,Tcs,Tlen1,Tline,Tcol,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,C1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{{Tline,Tcol},?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},{L1,C1}};
                     Ts == [] -> {eof,{L1,C1}};
                     true -> {ok,yyrev(Ts),{L1,C1}}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,C1,_S1} ->
            %% Skip rest of tokens.
            Error = {{L1,C1},?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, C1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_C1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline,Tcol),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            C2 = C0 + Alen1,
            tokens_cont(Tcs1, L2, C2, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Column, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

-dialyzer({nowarn_function, tokens_cont/5}).

tokens_cont(Rest, Line, Col, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, [T|Ts], reject, 0);
tokens_cont(Rest, Line, Col, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, [T|Ts], reject, 0);
tokens_cont(Rest, Line, Col, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),{Line,Col}},Rest};
tokens_cont(Rest, Line, Col, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),{Line, Col}},NewRest};
tokens_cont(Rest, Line, Col, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, Ts, reject, 0);
tokens_cont(Rest, Line, Col, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, Ts, reject, 0);
tokens_cont(Rest, Line, Col, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, Col, {{Line,Col},?MODULE,{user,S}}).

%% skip_tokens(InChars, Line, Col, Error) -> {done,{error,Error,{Line,Col}},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Col, Error) ->
    skip_tokens(yystate(), Ics, Line, Col, Ics, 0, Line, Col, Error, reject, 0).

%% skip_tokens(State, InChars, Line, Col, TokenChars, TokenLen, TokenLine, TokenCol, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, C0, Tcs, Tlen0, Tline, Tcol, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, C0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1, C1} ->                  % Accepting end state
            skip_cont(Ics1, L1, C1, yyaction(A1, Alen1, Tcs, Tline, Tcol), Error);
        {A1,Alen1,[],L1,C1, S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,C1,Tcs,Alen1,Tline,Tcol,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,C1,_S1} ->
            skip_cont(Ics1, L1, C1, yyaction(A1, Alen1, Tcs, Tline, Tcol), Error);
        {A1,Alen1,Tlen1,[],L1,C1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,C1,Tcs,Tlen1,Tline,Tcol,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,C1,_S1} ->
            {done,{error,Error,{L1,C1}},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,C1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, C1,Error);
        {A1,Alen1,Tlen1,_Ics1,L1,C1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline, Tcol),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            skip_cont(Tcs1, L2, C1, Token, Error)
    end.

%% skip_cont(RestChars, Line, Col, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

-dialyzer({nowarn_function, skip_cont/5}).

skip_cont(Rest, Line, Col, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, Error, reject, 0);
skip_cont(Rest, Line, Col, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, Error, reject, 0);
skip_cont(Rest, Line, Col, {end_token,_T}, Error) ->
    {done,{error,Error,{Line,Col}},Rest};
skip_cont(Rest, Line, Col, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,{Line,Col}},NewRest};
skip_cont(Rest, Line, Col, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, Error, reject, 0);
skip_cont(Rest, Line, Col, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, Error, reject, 0);
skip_cont(Rest, Line, Col, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, Error, reject, 0).

-compile({nowarn_unused_function, [yyrev/1, yyrev/2, yypre/2, yysuf/2]}).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% adjust_line(TokenLength, AcceptLength, Chars, Line) -> NewLine
%% Make sure that newlines in Chars are not counted twice.
%% Line has been updated with respect to newlines in the prefix of
%% Chars consisting of (TokenLength - AcceptLength) characters.

-compile({nowarn_unused_function, adjust_line/4}).

adjust_line(N, N, _Cs, L) -> L;
adjust_line(T, A, [$\n|Cs], L) ->
    adjust_line(T-1, A, Cs, L-1);
adjust_line(T, A, [_|Cs], L) ->
    adjust_line(T-1, A, Cs, L).

%% adjust_col(Chars, AcceptLength, Col) -> NewCol
%% Handle newlines, tabs and unicode chars.
adjust_col(_, 0, Col) ->
    Col;
adjust_col([$\n | R], L, _) ->
    adjust_col(R, L-1, 1);
adjust_col([$\t | R], L, Col) ->
    adjust_col(R, L-1, tab_forward(Col)+1);
adjust_col([C | R], L, Col) when C>=0 andalso C=< 16#7F ->
    adjust_col(R, L-1, Col+1);
adjust_col([C | R], L, Col) when C>= 16#80 andalso C=< 16#7FF ->
    adjust_col(R, L-1, Col+2);
adjust_col([C | R], L, Col) when C>= 16#800 andalso C=< 16#FFFF ->
    adjust_col(R, L-1, Col+3);
adjust_col([C | R], L, Col) when C>= 16#10000 andalso C=< 16#10FFFF ->
    adjust_col(R, L-1, Col+4).

tab_forward(C) ->
    D = C rem tab_size(),
    A = tab_size()-D,
    C+A.

tab_size() -> 8.

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, Col, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line, Col} |
%% {Action, AcceptLen, RestChars, Line, Col, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, Col, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, Col, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("src/mirage_css_tokenizer.erl", 387).
yystate() -> 48.

yystate(55, [61|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(55, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,55};
yystate(54, [95|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(34, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(54, [92|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(46, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(54, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(34, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(54, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(34, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(54, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 128 ->
    yystate(34, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(54, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,54};
yystate(53, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(40, Ics, Line, Col, Tlen+1, 14, Tlen);
yystate(53, [92|Ics], Line, Col, Tlen, _, _) ->
    yystate(32, Ics, Line, Col, Tlen+1, 14, Tlen);
yystate(53, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(40, Ics, Line, Col, Tlen+1, 14, Tlen);
yystate(53, [40|Ics], Line, Col, Tlen, _, _) ->
    yystate(24, Ics, Line, Col, Tlen+1, 14, Tlen);
yystate(53, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(37, Ics, Line, Col, Tlen+1, 14, Tlen);
yystate(53, [12|Ics], Line, Col, Tlen, _, _) ->
    yystate(37, Ics, Line, Col, Tlen+1, 14, Tlen);
yystate(53, [13|Ics], Line, Col, Tlen, _, _) ->
    yystate(37, Ics, Line, Col, Tlen+1, 14, Tlen);
yystate(53, [9|Ics], Line, Col, Tlen, _, _) ->
    yystate(37, Ics, Line, Col, Tlen+1, 14, Tlen);
yystate(53, [10|Ics], Line, _, Tlen, _, _) ->
    yystate(37, Ics, Line+1, 1, Tlen+1, 14, Tlen);
yystate(53, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(45, Ics, Line, Col, Tlen+1, 14, Tlen);
yystate(53, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Col, Tlen+1, 14, Tlen);
yystate(53, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(40, Ics, Line, Col, Tlen+1, 14, Tlen);
yystate(53, [C|Ics], Line, Col, Tlen, _, _) when C >= 128 ->
    yystate(40, Ics, Line, Col, Tlen+1, 14, Tlen);
yystate(53, Ics, Line, Col, Tlen, _, _) ->
    {14,Tlen,Ics,Line,Col,53};
yystate(52, [126|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(20, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(52, [124|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(52, [94|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(36, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(52, [93|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(31, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(52, [62|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(52, [44|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(30, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(52, [43|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(44, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(52, [41|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(52, [32|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(52, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(52, [12|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(52, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(52, [13|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(52, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(52, [9|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(52, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(52, [10|Ics], Line, _, Tlen, Action, Alen) ->
    yystate(52, Ics, Line+1, 1, Tlen+1, Action, Alen);
yystate(52, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,52};
yystate(51, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(40, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(51, [92|Ics], Line, Col, Tlen, _, _) ->
    yystate(32, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(51, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(53, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(51, [43|Ics], Line, Col, Tlen, _, _) ->
    yystate(37, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(51, [40|Ics], Line, Col, Tlen, _, _) ->
    yystate(24, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(51, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(21, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(51, [12|Ics], Line, Col, Tlen, _, _) ->
    yystate(21, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(51, [13|Ics], Line, Col, Tlen, _, _) ->
    yystate(21, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(51, [9|Ics], Line, Col, Tlen, _, _) ->
    yystate(21, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(51, [10|Ics], Line, _, Tlen, _, _) ->
    yystate(21, Ics, Line+1, 1, Tlen+1, 10, Tlen);
yystate(51, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(51, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(51, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(40, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(51, [C|Ics], Line, Col, Tlen, _, _) when C >= 128 ->
    yystate(40, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(51, Ics, Line, Col, Tlen, _, _) ->
    {10,Tlen,Ics,Line,Col,51};
yystate(50, [110|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(50, [95|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(50, [92|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(50, [78|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(50, [32|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(50, [12|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(50, [13|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(50, [9|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(50, [10|Ics], Line, _, Tlen, Action, Alen) ->
    yystate(38, Ics, Line+1, 1, Tlen+1, Action, Alen);
yystate(50, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(50, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 77 ->
    yystate(40, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(50, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 79, C =< 90 ->
    yystate(40, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(50, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 109 ->
    yystate(40, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(50, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 111, C =< 122 ->
    yystate(40, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(50, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 128 ->
    yystate(40, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(50, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,50};
yystate(49, [92|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(33, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(49, [39|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(11, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(49, [13|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(49, [12|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(49, [11|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(49, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(49, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(49, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 14, C =< 38 ->
    yystate(49, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(49, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 40, C =< 91 ->
    yystate(49, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(49, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 93 ->
    yystate(49, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(49, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,49};
yystate(48, [126|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(48, [124|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(48, [110|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(48, [95|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(48, [94|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(48, [93|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(31, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(48, [92|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(48, [91|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(43, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(48, [78|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(48, [62|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(48, [61|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(48, [58|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(2, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(48, [46|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(48, [45|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(48, [44|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(30, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(48, [43|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(22, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(48, [42|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(1, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(48, [41|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(48, [39|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(48, [36|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(55, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(48, [35|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(48, [34|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(4, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(48, [32|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(48, [13|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(52, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(48, [12|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(48, [9|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(52, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(48, [10|Ics], Line, _, Tlen, Action, Alen) ->
    yystate(52, Ics, Line+1, 1, Tlen+1, Action, Alen);
yystate(48, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(10, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(48, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 77 ->
    yystate(40, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(48, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 79, C =< 90 ->
    yystate(40, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(48, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 109 ->
    yystate(40, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(48, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 111, C =< 122 ->
    yystate(40, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(48, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 128 ->
    yystate(40, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(48, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,48};
yystate(47, Ics, Line, Col, Tlen, _, _) ->
    {5,Tlen,Ics,Line,Col};
yystate(46, [11|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(34, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(46, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(34, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(46, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 14 ->
    yystate(34, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(46, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,46};
yystate(45, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(40, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(45, [92|Ics], Line, Col, Tlen, _, _) ->
    yystate(32, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(45, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(40, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(45, [40|Ics], Line, Col, Tlen, _, _) ->
    yystate(24, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(45, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(45, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(45, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(45, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(40, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(45, [C|Ics], Line, Col, Tlen, _, _) when C >= 128 ->
    yystate(40, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(45, Ics, Line, Col, Tlen, _, _) ->
    {10,Tlen,Ics,Line,Col,45};
yystate(44, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(44, Ics, Line, Col, Tlen+1, 24, Tlen);
yystate(44, [12|Ics], Line, Col, Tlen, _, _) ->
    yystate(44, Ics, Line, Col, Tlen+1, 24, Tlen);
yystate(44, [13|Ics], Line, Col, Tlen, _, _) ->
    yystate(44, Ics, Line, Col, Tlen+1, 24, Tlen);
yystate(44, [9|Ics], Line, Col, Tlen, _, _) ->
    yystate(44, Ics, Line, Col, Tlen+1, 24, Tlen);
yystate(44, [10|Ics], Line, _, Tlen, _, _) ->
    yystate(44, Ics, Line+1, 1, Tlen+1, 24, Tlen);
yystate(44, Ics, Line, Col, Tlen, _, _) ->
    {24,Tlen,Ics,Line,Col,44};
yystate(43, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(43, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(43, [12|Ics], Line, Col, Tlen, _, _) ->
    yystate(43, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(43, [13|Ics], Line, Col, Tlen, _, _) ->
    yystate(43, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(43, [9|Ics], Line, Col, Tlen, _, _) ->
    yystate(43, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(43, [10|Ics], Line, _, Tlen, _, _) ->
    yystate(43, Ics, Line+1, 1, Tlen+1, 0, Tlen);
yystate(43, Ics, Line, Col, Tlen, _, _) ->
    {0,Tlen,Ics,Line,Col,43};
yystate(42, [110|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(18, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(42, [78|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(18, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(42, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(42, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,42};
yystate(41, [92|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(33, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(41, [39|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(11, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(41, [13|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(41, [12|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(41, [11|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(41, [10|Ics], Line, _, Tlen, Action, Alen) ->
    yystate(49, Ics, Line+1, 1, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(49, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 14, C =< 38 ->
    yystate(49, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 40, C =< 91 ->
    yystate(49, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 93 ->
    yystate(49, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(41, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,41};
yystate(40, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(40, Ics, Line, Col, Tlen+1, 14, Tlen);
yystate(40, [92|Ics], Line, Col, Tlen, _, _) ->
    yystate(32, Ics, Line, Col, Tlen+1, 14, Tlen);
yystate(40, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(40, Ics, Line, Col, Tlen+1, 14, Tlen);
yystate(40, [40|Ics], Line, Col, Tlen, _, _) ->
    yystate(24, Ics, Line, Col, Tlen+1, 14, Tlen);
yystate(40, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Col, Tlen+1, 14, Tlen);
yystate(40, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(40, Ics, Line, Col, Tlen+1, 14, Tlen);
yystate(40, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(40, Ics, Line, Col, Tlen+1, 14, Tlen);
yystate(40, [C|Ics], Line, Col, Tlen, _, _) when C >= 128 ->
    yystate(40, Ics, Line, Col, Tlen+1, 14, Tlen);
yystate(40, Ics, Line, Col, Tlen, _, _) ->
    {14,Tlen,Ics,Line,Col,40};
yystate(39, [95|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(27, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(39, [92|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(35, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(39, [45|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(27, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(39, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(27, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(39, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(27, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(39, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(27, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(39, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 128 ->
    yystate(27, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(39, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,39};
yystate(38, [110|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(18, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(38, [78|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(18, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(38, [32|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(38, [12|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(38, [13|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(38, [9|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(38, [10|Ics], Line, _, Tlen, Action, Alen) ->
    yystate(38, Ics, Line+1, 1, Tlen+1, Action, Alen);
yystate(38, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(38, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,38};
yystate(37, [32|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(37, [12|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(37, [13|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(37, [9|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(37, [10|Ics], Line, _, Tlen, Action, Alen) ->
    yystate(37, Ics, Line+1, 1, Tlen+1, Action, Alen);
yystate(37, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(29, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(37, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,37};
yystate(36, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(36, Ics, Line, Col, Tlen+1, 19, Tlen);
yystate(36, [12|Ics], Line, Col, Tlen, _, _) ->
    yystate(36, Ics, Line, Col, Tlen+1, 19, Tlen);
yystate(36, [13|Ics], Line, Col, Tlen, _, _) ->
    yystate(36, Ics, Line, Col, Tlen+1, 19, Tlen);
yystate(36, [9|Ics], Line, Col, Tlen, _, _) ->
    yystate(36, Ics, Line, Col, Tlen+1, 19, Tlen);
yystate(36, [10|Ics], Line, _, Tlen, _, _) ->
    yystate(36, Ics, Line+1, 1, Tlen+1, 19, Tlen);
yystate(36, Ics, Line, Col, Tlen, _, _) ->
    {19,Tlen,Ics,Line,Col,36};
yystate(35, [11|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(27, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(35, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(27, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(35, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 14 ->
    yystate(27, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(35, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,35};
yystate(34, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(34, Ics, Line, Col, Tlen+1, 15, Tlen);
yystate(34, [92|Ics], Line, Col, Tlen, _, _) ->
    yystate(46, Ics, Line, Col, Tlen+1, 15, Tlen);
yystate(34, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(34, Ics, Line, Col, Tlen+1, 15, Tlen);
yystate(34, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(34, Ics, Line, Col, Tlen+1, 15, Tlen);
yystate(34, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(34, Ics, Line, Col, Tlen+1, 15, Tlen);
yystate(34, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(34, Ics, Line, Col, Tlen+1, 15, Tlen);
yystate(34, [C|Ics], Line, Col, Tlen, _, _) when C >= 128 ->
    yystate(34, Ics, Line, Col, Tlen+1, 15, Tlen);
yystate(34, Ics, Line, Col, Tlen, _, _) ->
    {15,Tlen,Ics,Line,Col,34};
yystate(33, [11|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(33, [10|Ics], Line, _, Tlen, Action, Alen) ->
    yystate(49, Ics, Line+1, 1, Tlen+1, Action, Alen);
yystate(33, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(49, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(33, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 14 ->
    yystate(49, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(33, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,33};
yystate(32, [11|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(32, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(40, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(32, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 14 ->
    yystate(40, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(32, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,32};
yystate(31, Ics, Line, Col, Tlen, _, _) ->
    {1,Tlen,Ics,Line,Col};
yystate(30, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(30, Ics, Line, Col, Tlen+1, 21, Tlen);
yystate(30, [12|Ics], Line, Col, Tlen, _, _) ->
    yystate(30, Ics, Line, Col, Tlen+1, 21, Tlen);
yystate(30, [13|Ics], Line, Col, Tlen, _, _) ->
    yystate(30, Ics, Line, Col, Tlen+1, 21, Tlen);
yystate(30, [9|Ics], Line, Col, Tlen, _, _) ->
    yystate(30, Ics, Line, Col, Tlen+1, 21, Tlen);
yystate(30, [10|Ics], Line, _, Tlen, _, _) ->
    yystate(30, Ics, Line+1, 1, Tlen+1, 21, Tlen);
yystate(30, Ics, Line, Col, Tlen, _, _) ->
    {21,Tlen,Ics,Line,Col,30};
yystate(29, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(29, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(29, Ics, Line, Col, Tlen, _, _) ->
    {10,Tlen,Ics,Line,Col,29};
yystate(28, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(28, Ics, Line, Col, Tlen+1, 20, Tlen);
yystate(28, [12|Ics], Line, Col, Tlen, _, _) ->
    yystate(28, Ics, Line, Col, Tlen+1, 20, Tlen);
yystate(28, [13|Ics], Line, Col, Tlen, _, _) ->
    yystate(28, Ics, Line, Col, Tlen+1, 20, Tlen);
yystate(28, [9|Ics], Line, Col, Tlen, _, _) ->
    yystate(28, Ics, Line, Col, Tlen+1, 20, Tlen);
yystate(28, [10|Ics], Line, _, Tlen, _, _) ->
    yystate(28, Ics, Line+1, 1, Tlen+1, 20, Tlen);
yystate(28, Ics, Line, Col, Tlen, _, _) ->
    {20,Tlen,Ics,Line,Col,28};
yystate(27, [95|Ics], Line, Col, Tlen, _, _) ->
    yystate(27, Ics, Line, Col, Tlen+1, 16, Tlen);
yystate(27, [92|Ics], Line, Col, Tlen, _, _) ->
    yystate(35, Ics, Line, Col, Tlen+1, 16, Tlen);
yystate(27, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(27, Ics, Line, Col, Tlen+1, 16, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(27, Ics, Line, Col, Tlen+1, 16, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(27, Ics, Line, Col, Tlen+1, 16, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(27, Ics, Line, Col, Tlen+1, 16, Tlen);
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 128 ->
    yystate(27, Ics, Line, Col, Tlen+1, 16, Tlen);
yystate(27, Ics, Line, Col, Tlen, _, _) ->
    {16,Tlen,Ics,Line,Col,27};
yystate(26, [95|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(34, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(26, [92|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(46, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(26, [45|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(54, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(26, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(34, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(26, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(34, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(26, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 128 ->
    yystate(34, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(26, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,26};
yystate(25, Ics, Line, Col, Tlen, _, _) ->
    {2,Tlen,Ics,Line,Col};
yystate(24, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(24, Ics, Line, Col, Tlen+1, 9, Tlen);
yystate(24, [12|Ics], Line, Col, Tlen, _, _) ->
    yystate(24, Ics, Line, Col, Tlen+1, 9, Tlen);
yystate(24, [13|Ics], Line, Col, Tlen, _, _) ->
    yystate(24, Ics, Line, Col, Tlen+1, 9, Tlen);
yystate(24, [9|Ics], Line, Col, Tlen, _, _) ->
    yystate(24, Ics, Line, Col, Tlen+1, 9, Tlen);
yystate(24, [10|Ics], Line, _, Tlen, _, _) ->
    yystate(24, Ics, Line+1, 1, Tlen+1, 9, Tlen);
yystate(24, Ics, Line, Col, Tlen, _, _) ->
    {9,Tlen,Ics,Line,Col,24};
yystate(23, Ics, Line, Col, Tlen, _, _) ->
    {6,Tlen,Ics,Line,Col};
yystate(22, [110|Ics], Line, Col, Tlen, _, _) ->
    yystate(18, Ics, Line, Col, Tlen+1, 24, Tlen);
yystate(22, [78|Ics], Line, Col, Tlen, _, _) ->
    yystate(18, Ics, Line, Col, Tlen+1, 24, Tlen);
yystate(22, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(6, Ics, Line, Col, Tlen+1, 24, Tlen);
yystate(22, [12|Ics], Line, Col, Tlen, _, _) ->
    yystate(6, Ics, Line, Col, Tlen+1, 24, Tlen);
yystate(22, [13|Ics], Line, Col, Tlen, _, _) ->
    yystate(6, Ics, Line, Col, Tlen+1, 24, Tlen);
yystate(22, [9|Ics], Line, Col, Tlen, _, _) ->
    yystate(6, Ics, Line, Col, Tlen+1, 24, Tlen);
yystate(22, [10|Ics], Line, _, Tlen, _, _) ->
    yystate(6, Ics, Line+1, 1, Tlen+1, 24, Tlen);
yystate(22, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(14, Ics, Line, Col, Tlen+1, 24, Tlen);
yystate(22, Ics, Line, Col, Tlen, _, _) ->
    {24,Tlen,Ics,Line,Col,22};
yystate(21, [45|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(21, [43|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(21, [32|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(21, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(21, [12|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(21, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(21, [13|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(21, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(21, [9|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(21, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(21, [10|Ics], Line, _, Tlen, Action, Alen) ->
    yystate(21, Ics, Line+1, 1, Tlen+1, Action, Alen);
yystate(21, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,21};
yystate(20, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(20, Ics, Line, Col, Tlen+1, 23, Tlen);
yystate(20, [12|Ics], Line, Col, Tlen, _, _) ->
    yystate(20, Ics, Line, Col, Tlen+1, 23, Tlen);
yystate(20, [13|Ics], Line, Col, Tlen, _, _) ->
    yystate(20, Ics, Line, Col, Tlen+1, 23, Tlen);
yystate(20, [9|Ics], Line, Col, Tlen, _, _) ->
    yystate(20, Ics, Line, Col, Tlen+1, 23, Tlen);
yystate(20, [10|Ics], Line, _, Tlen, _, _) ->
    yystate(20, Ics, Line+1, 1, Tlen+1, 23, Tlen);
yystate(20, Ics, Line, Col, Tlen, _, _) ->
    {23,Tlen,Ics,Line,Col,20};
yystate(19, [11|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(4, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(19, [10|Ics], Line, _, Tlen, Action, Alen) ->
    yystate(4, Ics, Line+1, 1, Tlen+1, Action, Alen);
yystate(19, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(4, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(19, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 14 ->
    yystate(4, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(19, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,19};
yystate(18, [45|Ics], Line, Col, Tlen, _, _) ->
    yystate(37, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(18, [43|Ics], Line, Col, Tlen, _, _) ->
    yystate(37, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(18, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(21, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(18, [12|Ics], Line, Col, Tlen, _, _) ->
    yystate(21, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(18, [13|Ics], Line, Col, Tlen, _, _) ->
    yystate(21, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(18, [9|Ics], Line, Col, Tlen, _, _) ->
    yystate(21, Ics, Line, Col, Tlen+1, 10, Tlen);
yystate(18, [10|Ics], Line, _, Tlen, _, _) ->
    yystate(21, Ics, Line+1, 1, Tlen+1, 10, Tlen);
yystate(18, Ics, Line, Col, Tlen, _, _) ->
    {10,Tlen,Ics,Line,Col,18};
yystate(17, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(17, Ics, Line, Col, Tlen+1, 18, Tlen);
yystate(17, [12|Ics], Line, Col, Tlen, _, _) ->
    yystate(17, Ics, Line, Col, Tlen+1, 18, Tlen);
yystate(17, [13|Ics], Line, Col, Tlen, _, _) ->
    yystate(17, Ics, Line, Col, Tlen+1, 18, Tlen);
yystate(17, [9|Ics], Line, Col, Tlen, _, _) ->
    yystate(17, Ics, Line, Col, Tlen+1, 18, Tlen);
yystate(17, [10|Ics], Line, _, Tlen, _, _) ->
    yystate(17, Ics, Line+1, 1, Tlen+1, 18, Tlen);
yystate(17, Ics, Line, Col, Tlen, _, _) ->
    {18,Tlen,Ics,Line,Col,17};
yystate(16, [61|Ics], Line, Col, Tlen, _, _) ->
    yystate(8, Ics, Line, Col, Tlen+1, 23, Tlen);
yystate(16, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(20, Ics, Line, Col, Tlen+1, 23, Tlen);
yystate(16, [12|Ics], Line, Col, Tlen, _, _) ->
    yystate(20, Ics, Line, Col, Tlen+1, 23, Tlen);
yystate(16, [13|Ics], Line, Col, Tlen, _, _) ->
    yystate(20, Ics, Line, Col, Tlen+1, 23, Tlen);
yystate(16, [9|Ics], Line, Col, Tlen, _, _) ->
    yystate(20, Ics, Line, Col, Tlen+1, 23, Tlen);
yystate(16, [10|Ics], Line, _, Tlen, _, _) ->
    yystate(20, Ics, Line+1, 1, Tlen+1, 23, Tlen);
yystate(16, Ics, Line, Col, Tlen, _, _) ->
    {23,Tlen,Ics,Line,Col,16};
yystate(15, [61|Ics], Line, Col, Tlen, _, _) ->
    yystate(23, Ics, Line, Col, Tlen+1, 19, Tlen);
yystate(15, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(36, Ics, Line, Col, Tlen+1, 19, Tlen);
yystate(15, [12|Ics], Line, Col, Tlen, _, _) ->
    yystate(36, Ics, Line, Col, Tlen+1, 19, Tlen);
yystate(15, [13|Ics], Line, Col, Tlen, _, _) ->
    yystate(36, Ics, Line, Col, Tlen+1, 19, Tlen);
yystate(15, [9|Ics], Line, Col, Tlen, _, _) ->
    yystate(36, Ics, Line, Col, Tlen+1, 19, Tlen);
yystate(15, [10|Ics], Line, _, Tlen, _, _) ->
    yystate(36, Ics, Line+1, 1, Tlen+1, 19, Tlen);
yystate(15, Ics, Line, Col, Tlen, _, _) ->
    {19,Tlen,Ics,Line,Col,15};
yystate(14, [110|Ics], Line, Col, Tlen, _, _) ->
    yystate(18, Ics, Line, Col, Tlen+1, 11, Tlen);
yystate(14, [78|Ics], Line, Col, Tlen, _, _) ->
    yystate(18, Ics, Line, Col, Tlen+1, 11, Tlen);
yystate(14, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(14, Ics, Line, Col, Tlen+1, 11, Tlen);
yystate(14, Ics, Line, Col, Tlen, _, _) ->
    {11,Tlen,Ics,Line,Col,14};
yystate(13, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(13, Ics, Line, Col, Tlen+1, 22, Tlen);
yystate(13, [12|Ics], Line, Col, Tlen, _, _) ->
    yystate(13, Ics, Line, Col, Tlen+1, 22, Tlen);
yystate(13, [13|Ics], Line, Col, Tlen, _, _) ->
    yystate(13, Ics, Line, Col, Tlen+1, 22, Tlen);
yystate(13, [9|Ics], Line, Col, Tlen, _, _) ->
    yystate(13, Ics, Line, Col, Tlen+1, 22, Tlen);
yystate(13, [10|Ics], Line, _, Tlen, _, _) ->
    yystate(13, Ics, Line+1, 1, Tlen+1, 22, Tlen);
yystate(13, Ics, Line, Col, Tlen, _, _) ->
    {22,Tlen,Ics,Line,Col,13};
yystate(12, [126|Ics], Line, Col, Tlen, _, _) ->
    yystate(20, Ics, Line, Col, Tlen+1, 25, Tlen);
yystate(12, [124|Ics], Line, Col, Tlen, _, _) ->
    yystate(28, Ics, Line, Col, Tlen+1, 25, Tlen);
yystate(12, [94|Ics], Line, Col, Tlen, _, _) ->
    yystate(36, Ics, Line, Col, Tlen+1, 25, Tlen);
yystate(12, [93|Ics], Line, Col, Tlen, _, _) ->
    yystate(31, Ics, Line, Col, Tlen+1, 25, Tlen);
yystate(12, [62|Ics], Line, Col, Tlen, _, _) ->
    yystate(13, Ics, Line, Col, Tlen+1, 25, Tlen);
yystate(12, [44|Ics], Line, Col, Tlen, _, _) ->
    yystate(30, Ics, Line, Col, Tlen+1, 25, Tlen);
yystate(12, [43|Ics], Line, Col, Tlen, _, _) ->
    yystate(44, Ics, Line, Col, Tlen+1, 25, Tlen);
yystate(12, [41|Ics], Line, Col, Tlen, _, _) ->
    yystate(25, Ics, Line, Col, Tlen+1, 25, Tlen);
yystate(12, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(12, Ics, Line, Col, Tlen+1, 25, Tlen);
yystate(12, [13|Ics], Line, Col, Tlen, _, _) ->
    yystate(52, Ics, Line, Col, Tlen+1, 25, Tlen);
yystate(12, [12|Ics], Line, Col, Tlen, _, _) ->
    yystate(12, Ics, Line, Col, Tlen+1, 25, Tlen);
yystate(12, [9|Ics], Line, Col, Tlen, _, _) ->
    yystate(52, Ics, Line, Col, Tlen+1, 25, Tlen);
yystate(12, [10|Ics], Line, _, Tlen, _, _) ->
    yystate(52, Ics, Line+1, 1, Tlen+1, 25, Tlen);
yystate(12, Ics, Line, Col, Tlen, _, _) ->
    {25,Tlen,Ics,Line,Col,12};
yystate(11, Ics, Line, Col, Tlen, _, _) ->
    {13,Tlen,Ics,Line,Col};
yystate(10, [110|Ics], Line, Col, Tlen, _, _) ->
    yystate(18, Ics, Line, Col, Tlen+1, 12, Tlen);
yystate(10, [78|Ics], Line, Col, Tlen, _, _) ->
    yystate(18, Ics, Line, Col, Tlen+1, 12, Tlen);
yystate(10, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(10, Ics, Line, Col, Tlen+1, 12, Tlen);
yystate(10, Ics, Line, Col, Tlen, _, _) ->
    {12,Tlen,Ics,Line,Col,10};
yystate(9, Ics, Line, Col, Tlen, _, _) ->
    {7,Tlen,Ics,Line,Col};
yystate(8, Ics, Line, Col, Tlen, _, _) ->
    {3,Tlen,Ics,Line,Col};
yystate(7, Ics, Line, Col, Tlen, _, _) ->
    {4,Tlen,Ics,Line,Col};
yystate(6, [110|Ics], Line, Col, Tlen, _, _) ->
    yystate(18, Ics, Line, Col, Tlen+1, 24, Tlen);
yystate(6, [78|Ics], Line, Col, Tlen, _, _) ->
    yystate(18, Ics, Line, Col, Tlen+1, 24, Tlen);
yystate(6, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(6, Ics, Line, Col, Tlen+1, 24, Tlen);
yystate(6, [12|Ics], Line, Col, Tlen, _, _) ->
    yystate(6, Ics, Line, Col, Tlen+1, 24, Tlen);
yystate(6, [13|Ics], Line, Col, Tlen, _, _) ->
    yystate(6, Ics, Line, Col, Tlen+1, 24, Tlen);
yystate(6, [9|Ics], Line, Col, Tlen, _, _) ->
    yystate(6, Ics, Line, Col, Tlen+1, 24, Tlen);
yystate(6, [10|Ics], Line, _, Tlen, _, _) ->
    yystate(6, Ics, Line+1, 1, Tlen+1, 24, Tlen);
yystate(6, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Col, Tlen+1, 24, Tlen);
yystate(6, Ics, Line, Col, Tlen, _, _) ->
    {24,Tlen,Ics,Line,Col,6};
yystate(5, Ics, Line, Col, Tlen, _, _) ->
    {8,Tlen,Ics,Line,Col};
yystate(4, [92|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(4, [34|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(11, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(4, [13|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(4, [12|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(4, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(4, [11|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(4, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(4, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(4, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(4, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 14, C =< 33 ->
    yystate(4, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(4, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(4, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(4, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 93 ->
    yystate(4, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(4, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,4};
yystate(3, [92|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(3, [34|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(11, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(3, [13|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(3, [12|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(4, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(3, [11|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(4, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(3, [10|Ics], Line, _, Tlen, Action, Alen) ->
    yystate(4, Ics, Line+1, 1, Tlen+1, Action, Alen);
yystate(3, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(4, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(3, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 14, C =< 33 ->
    yystate(4, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(3, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(4, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(3, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 93 ->
    yystate(4, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(3, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,3};
yystate(2, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(2, Ics, Line, Col, Tlen+1, 17, Tlen);
yystate(2, [12|Ics], Line, Col, Tlen, _, _) ->
    yystate(2, Ics, Line, Col, Tlen+1, 17, Tlen);
yystate(2, [13|Ics], Line, Col, Tlen, _, _) ->
    yystate(2, Ics, Line, Col, Tlen+1, 17, Tlen);
yystate(2, [9|Ics], Line, Col, Tlen, _, _) ->
    yystate(2, Ics, Line, Col, Tlen+1, 17, Tlen);
yystate(2, [10|Ics], Line, _, Tlen, _, _) ->
    yystate(2, Ics, Line+1, 1, Tlen+1, 17, Tlen);
yystate(2, Ics, Line, Col, Tlen, _, _) ->
    {17,Tlen,Ics,Line,Col,2};
yystate(1, [61|Ics], Line, Col, Tlen, _, _) ->
    yystate(9, Ics, Line, Col, Tlen+1, 18, Tlen);
yystate(1, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(17, Ics, Line, Col, Tlen+1, 18, Tlen);
yystate(1, [12|Ics], Line, Col, Tlen, _, _) ->
    yystate(17, Ics, Line, Col, Tlen+1, 18, Tlen);
yystate(1, [13|Ics], Line, Col, Tlen, _, _) ->
    yystate(17, Ics, Line, Col, Tlen+1, 18, Tlen);
yystate(1, [9|Ics], Line, Col, Tlen, _, _) ->
    yystate(17, Ics, Line, Col, Tlen+1, 18, Tlen);
yystate(1, [10|Ics], Line, _, Tlen, _, _) ->
    yystate(17, Ics, Line+1, 1, Tlen+1, 18, Tlen);
yystate(1, Ics, Line, Col, Tlen, _, _) ->
    {18,Tlen,Ics,Line,Col,1};
yystate(0, [61|Ics], Line, Col, Tlen, _, _) ->
    yystate(7, Ics, Line, Col, Tlen+1, 20, Tlen);
yystate(0, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(28, Ics, Line, Col, Tlen+1, 20, Tlen);
yystate(0, [12|Ics], Line, Col, Tlen, _, _) ->
    yystate(28, Ics, Line, Col, Tlen+1, 20, Tlen);
yystate(0, [13|Ics], Line, Col, Tlen, _, _) ->
    yystate(28, Ics, Line, Col, Tlen+1, 20, Tlen);
yystate(0, [9|Ics], Line, Col, Tlen, _, _) ->
    yystate(28, Ics, Line, Col, Tlen+1, 20, Tlen);
yystate(0, [10|Ics], Line, _, Tlen, _, _) ->
    yystate(28, Ics, Line+1, 1, Tlen+1, 20, Tlen);
yystate(0, Ics, Line, Col, Tlen, _, _) ->
    {20,Tlen,Ics,Line,Col,0};
yystate(S, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine, TokenCol) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, _, _, _, _) ->
    yyaction_0();
yyaction(1, _, _, _, _) ->
    yyaction_1();
yyaction(2, _, _, _, _) ->
    yyaction_2();
yyaction(3, _, _, _, _) ->
    yyaction_3();
yyaction(4, _, _, _, _) ->
    yyaction_4();
yyaction(5, _, _, _, _) ->
    yyaction_5();
yyaction(6, _, _, _, _) ->
    yyaction_6();
yyaction(7, _, _, _, _) ->
    yyaction_7();
yyaction(8, _, _, _, _) ->
    yyaction_8();
yyaction(9, TokenLen, YYtcs, _, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_9(TokenChars);
yyaction(10, TokenLen, YYtcs, _, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_10(TokenChars);
yyaction(11, TokenLen, YYtcs, _, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_11(TokenChars);
yyaction(12, TokenLen, YYtcs, _, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_12(TokenChars);
yyaction(13, TokenLen, YYtcs, _, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_13(TokenChars);
yyaction(14, TokenLen, YYtcs, _, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_14(TokenChars);
yyaction(15, TokenLen, YYtcs, _, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_15(TokenChars);
yyaction(16, TokenLen, YYtcs, _, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_16(TokenChars);
yyaction(17, _, _, _, _) ->
    yyaction_17();
yyaction(18, _, _, _, _) ->
    yyaction_18();
yyaction(19, _, _, _, _) ->
    yyaction_19();
yyaction(20, _, _, _, _) ->
    yyaction_20();
yyaction(21, _, _, _, _) ->
    yyaction_21();
yyaction(22, _, _, _, _) ->
    yyaction_22();
yyaction(23, _, _, _, _) ->
    yyaction_23();
yyaction(24, _, _, _, _) ->
    yyaction_24();
yyaction(25, _, _, _, _) ->
    yyaction_25();
yyaction(_, _, _, _, _) -> error.

-compile({inline,yyaction_0/0}).
-file("src/mirage_css_tokenizer.xrl", 23).
yyaction_0() ->
     { token, "[" } .

-compile({inline,yyaction_1/0}).
-file("src/mirage_css_tokenizer.xrl", 24).
yyaction_1() ->
     { token, "]" } .

-compile({inline,yyaction_2/0}).
-file("src/mirage_css_tokenizer.xrl", 25).
yyaction_2() ->
     { token, ")" } .

-compile({inline,yyaction_3/0}).
-file("src/mirage_css_tokenizer.xrl", 27).
yyaction_3() ->
     { token, value_includes } .

-compile({inline,yyaction_4/0}).
-file("src/mirage_css_tokenizer.xrl", 28).
yyaction_4() ->
     { token, value_dash } .

-compile({inline,yyaction_5/0}).
-file("src/mirage_css_tokenizer.xrl", 29).
yyaction_5() ->
     { token, value_suffix } .

-compile({inline,yyaction_6/0}).
-file("src/mirage_css_tokenizer.xrl", 30).
yyaction_6() ->
     { token, value_prefix } .

-compile({inline,yyaction_7/0}).
-file("src/mirage_css_tokenizer.xrl", 31).
yyaction_7() ->
     { token, value_contains } .

-compile({inline,yyaction_8/0}).
-file("src/mirage_css_tokenizer.xrl", 32).
yyaction_8() ->
     { token, value } .

-compile({inline,yyaction_9/1}).
-file("src/mirage_css_tokenizer.xrl", 34).
yyaction_9(TokenChars) ->
     { token, { function, without_escapes (trim_and_drop_last (TokenChars)) } } .

-compile({inline,yyaction_10/1}).
-file("src/mirage_css_tokenizer.xrl", 35).
yyaction_10(TokenChars) ->
     { token, { ab_formula, TokenChars } } .

-compile({inline,yyaction_11/1}).
-file("src/mirage_css_tokenizer.xrl", 36).
yyaction_11(TokenChars) ->
     { token, { int, drop_first (TokenChars) } } .

-compile({inline,yyaction_12/1}).
-file("src/mirage_css_tokenizer.xrl", 37).
yyaction_12(TokenChars) ->
     { token, { int, TokenChars } } .

-compile({inline,yyaction_13/1}).
-file("src/mirage_css_tokenizer.xrl", 38).
yyaction_13(TokenChars) ->
     { token, { string, without_escapes (remove_quotes (TokenChars)) } } .

-compile({inline,yyaction_14/1}).
-file("src/mirage_css_tokenizer.xrl", 39).
yyaction_14(TokenChars) ->
     { token, { ident, without_escapes (TokenChars) } } .

-compile({inline,yyaction_15/1}).
-file("src/mirage_css_tokenizer.xrl", 41).
yyaction_15(TokenChars) ->
     { token, { class, without_escapes (drop_first (TokenChars)) } } .

-compile({inline,yyaction_16/1}).
-file("src/mirage_css_tokenizer.xrl", 42).
yyaction_16(TokenChars) ->
     { token, { id, without_escapes (drop_first (TokenChars)) } } .

-compile({inline,yyaction_17/0}).
-file("src/mirage_css_tokenizer.xrl", 45).
yyaction_17() ->
     { token, ":" } .

-compile({inline,yyaction_18/0}).
-file("src/mirage_css_tokenizer.xrl", 46).
yyaction_18() ->
     { token, "*" } .

-compile({inline,yyaction_19/0}).
-file("src/mirage_css_tokenizer.xrl", 48).
yyaction_19() ->
     { token, "^" } .

-compile({inline,yyaction_20/0}).
-file("src/mirage_css_tokenizer.xrl", 49).
yyaction_20() ->
     { token, "|" } .

-compile({inline,yyaction_21/0}).
-file("src/mirage_css_tokenizer.xrl", 50).
yyaction_21() ->
     { token, "," } .

-compile({inline,yyaction_22/0}).
-file("src/mirage_css_tokenizer.xrl", 52).
yyaction_22() ->
     { token, ">" } .

-compile({inline,yyaction_23/0}).
-file("src/mirage_css_tokenizer.xrl", 53).
yyaction_23() ->
     { token, "~" } .

-compile({inline,yyaction_24/0}).
-file("src/mirage_css_tokenizer.xrl", 54).
yyaction_24() ->
     { token, "+" } .

-compile({inline,yyaction_25/0}).
-file("src/mirage_css_tokenizer.xrl", 55).
yyaction_25() ->
     { token, space } .
-file("/Users/andrwe/.asdf/installs/erlang/28.4.1/lib/parsetools-2.7.1/include/leexinc.hrl", 377).
